/* Generated by RbxNetIdGen */

export const enum RemoteId {
	NewGame = "225cacf7-e8e9-459d-aedc-bd035bc8111d",
	Continue = "36eb7d23-93b6-451a-bdf3-41c88b65f033",
	SaveFile = "5db8f1d2-489a-4121-9cde-078626f26d31",
	LoadFile = "55dd6c44-db03-4469-a0fe-81a6eb324161",
	DeleteSave = "d14462d8-6c7e-4218-8cdb-ae37464cd314",
	PickUp = "13d7b6d0-d185-48dd-8dae-a8fe1e89fd8e",
}
