/* Generated by RbxNetIdGen */

export const enum RemoteId {
    Ready = "fa54d8d8-ab6d-450c-9062-da5b522d846c",
    Spawn = "c6162093-6967-47e5-850f-521f122eed2e",
    PickUp = "0b8fd775-c7d0-4dde-a1bf-3e0bd5cc7ed9"
}
